ALTER TABLE "ChatMessage" ALTER COLUMN "role" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ChatMessage" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ChatMessage" ALTER COLUMN "createdAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ChatSession" ALTER COLUMN "type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ChatSession" ALTER COLUMN "isArchived" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ChatSession" ALTER COLUMN "createdAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ChatSession" ALTER COLUMN "updatedAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Comment" ALTER COLUMN "createdAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "FeedPost" ALTER COLUMN "likeCount" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "FeedPost" ALTER COLUMN "context" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "FeedPost" ALTER COLUMN "publishedLabel" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "FeedPost" ALTER COLUMN "createdAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "FeedPost" ALTER COLUMN "updatedAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "LlmProvider" ALTER COLUMN "createdAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "PostAttachment" ALTER COLUMN "order" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "SessionParticipant" ALTER COLUMN "role" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "SessionParticipant" ALTER COLUMN "joinedAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "SocialAffinity" ALTER COLUMN "score" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "SystemConfig" ALTER COLUMN "isInitialized" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "SystemConfig" ALTER COLUMN "createdAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "SystemConfig" ALTER COLUMN "updatedAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "User" ALTER COLUMN "type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "User" ALTER COLUMN "createdAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "User" ALTER COLUMN "updatedAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Workflow" ALTER COLUMN "createdAt" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ChatMessage" ADD COLUMN "userId" uuid NOT NULL;