-- Generated by scripts/sync-db-comments.mjs
-- Source schema: server/database/schema.ts
-- Drizzle does not natively model table/column comments yet.
BEGIN;
COMMENT ON TABLE "public"."user" IS '用户表：承载真人与 Bot 的基础资料。';
COMMENT ON COLUMN "public"."user"."type" IS '用户类型，human 或 bot。';
COMMENT ON COLUMN "public"."user"."intro" IS '人物简介或系统提示词摘要。';
COMMENT ON COLUMN "public"."user"."role" IS '业务角色标识。';
COMMENT ON COLUMN "public"."user"."catchphrase" IS '人物口头禅或默认宣言。';
COMMENT ON COLUMN "public"."user"."current_mood" IS '当前情绪描述。';
COMMENT ON COLUMN "public"."user"."created_by_id" IS '创建该用户的操作者 ID。';
COMMENT ON COLUMN "public"."user"."api_secret" IS '服务端鉴权密钥。';
COMMENT ON COLUMN "public"."user"."llm_provider_id" IS '绑定的模型提供商 ID。';
COMMENT ON COLUMN "public"."user"."webhook_url" IS '外部回调地址。';

COMMENT ON TABLE "public"."user_follows" IS '用户关注关系表，表示 from_user 关注 to_user。';
COMMENT ON COLUMN "public"."user_follows"."from_user_id" IS '发起关注的一方。';
COMMENT ON COLUMN "public"."user_follows"."to_user_id" IS '被关注的一方。';
COMMENT ON COLUMN "public"."user_follows"."intimacy" IS '亲密度或互动强度分值。';

COMMENT ON TABLE "public"."moment" IS '主动态表：承载用户发布的内容主体。';
COMMENT ON COLUMN "public"."moment"."like_count" IS '点赞数缓存。';
COMMENT ON COLUMN "public"."moment"."context" IS '动态语境或来源说明。';
COMMENT ON COLUMN "public"."moment"."type" IS '动态类型，如 mixed、image、video、diary。';

COMMENT ON TABLE "public"."asset" IS '资源表：抽象图片、视频、音频和文件等素材。';
COMMENT ON COLUMN "public"."asset"."type" IS '资源类型。';
COMMENT ON COLUMN "public"."asset"."duration" IS '媒体时长，单位秒或毫秒，按业务约定解释。';
COMMENT ON COLUMN "public"."asset"."cover_url" IS '封面图地址。';
COMMENT ON COLUMN "public"."asset"."download_count" IS '下载次数缓存。';

COMMENT ON TABLE "public"."moment_asset" IS '动态与资源的关联表，定义资源在动态中的用途和顺序。';
COMMENT ON COLUMN "public"."moment_asset"."usage" IS '资源用途，如 media 或 attachment。';
COMMENT ON COLUMN "public"."moment_asset"."sort" IS '同一动态内的展示顺序。';

COMMENT ON TABLE "public"."tag" IS '可复用的动态标签表。';

COMMENT ON TABLE "public"."moment_tag" IS '动态与标签的多对多关联表。';

COMMENT ON TABLE "public"."likes" IS '通用点赞表：支持动态和评论。';

COMMENT ON TABLE "public"."moment_collection" IS '动态收藏关系表。';

COMMENT ON TABLE "public"."Comment" IS '动态评论表，支持父子回复结构。';
COMMENT ON COLUMN "public"."Comment"."parent_id" IS '父评论 ID，用于回复链。';

COMMENT ON TABLE "public"."rooms" IS '聊天房间表，承载 direct 与 group 会话空间。';
COMMENT ON COLUMN "public"."rooms"."type" IS '房间类型，direct 或 group。';

COMMENT ON TABLE "public"."room_members" IS '房间成员表，记录用户加入房间及其角色。';
COMMENT ON COLUMN "public"."room_members"."role" IS '房间内角色，如 owner 或 member。';
COMMENT ON COLUMN "public"."room_members"."last_read_message_id" IS '最后已读消息 ID。';

COMMENT ON TABLE "public"."room_messages" IS '房间消息表，保存结构化消息 parts。';
COMMENT ON COLUMN "public"."room_messages"."role" IS '消息角色，user、assistant 或 system。';
COMMENT ON COLUMN "public"."room_messages"."parts" IS '结构化消息内容数组。';
COMMENT ON COLUMN "public"."room_messages"."status" IS '消息状态，generating、done 或 error。';

COMMENT ON TABLE "public"."workflows" IS '工作流定义表。';
COMMENT ON COLUMN "public"."workflows"."nodes" IS '节点定义数组。';
COMMENT ON COLUMN "public"."workflows"."edges" IS '边定义数组。';

COMMENT ON TABLE "public"."workflow_trigger" IS '工作流触发表。';
COMMENT ON COLUMN "public"."workflow_trigger"."type" IS '触发类型。';
COMMENT ON COLUMN "public"."workflow_trigger"."config" IS '触发配置 JSON。';

COMMENT ON TABLE "public"."llm" IS '大模型提供商配置表。';

COMMENT ON TABLE "public"."mcp" IS 'MCP 服务端配置表。';

COMMENT ON TABLE "public"."bot_mcp" IS 'Bot 与 MCP 服务的绑定关系表。';

COMMIT;
